/*
 * DMA_config.h
 *
 *  Created on: 23 Aug 2022
 *      Author: es-RaghadAly2023
 */

#ifndef DMA_CONFIG_H_
#define DMA_CONFIG_H_




typedef struct{

	u8 mem2mem;
	u8 pl;
	u8 msize;
	u8 psize;
	u8 minc;
	u8 pinc;
	u8 circ;
	u8 dir;
	u8 teie;
	u8 htie;
	u8 tcie;

}DMA_Config_t;





/* Enable or Disable the memory to memory mode
 * Options: 1-DMA_DISABLE
 * 			2-DMA_ENABLE
 **/
#define DMA_CHANNEL0_MEMORY_TO_MEMORY_MODE				DMA_DISABLE
#define DMA_CHANNEL1_MEMORY_TO_MEMORY_MODE				DMA_ENABLE
#define DMA_CHANNEL2_MEMORY_TO_MEMORY_MODE				DMA_ENABLE
#define DMA_CHANNEL3_MEMORY_TO_MEMORY_MODE				DMA_DISABLE
#define DMA_CHANNEL4_MEMORY_TO_MEMORY_MODE				DMA_ENABLE
#define DMA_CHANNEL5_MEMORY_TO_MEMORY_MODE				DMA_ENABLE
#define DMA_CHANNEL6_MEMORY_TO_MEMORY_MODE				DMA_ENABLE


/* Select the Channel Priority Level
 * Options: 1-DMA_CHANNEL_PRIORITY_LOW
 * 			2-DMA_CHANNEL_PRIORITY_MEDIUM
 * 			3-DMA_CHANNEL_PRIORITY_HIGH
 * 			4-DMA_CHANNEL_PRIORITY_VERY_HIGH
 **/
#define DMA_CHANNEL0_PRIORITY_LEVEL					DMA_CHANNEL_PRIORITY_VERY_HIGH
#define DMA_CHANNEL1_PRIORITY_LEVEL					DMA_CHANNEL_PRIORITY_VERY_HIGH
#define DMA_CHANNEL2_PRIORITY_LEVEL					DMA_CHANNEL_PRIORITY_VERY_HIGH
#define DMA_CHANNEL3_PRIORITY_LEVEL					DMA_CHANNEL_PRIORITY_VERY_HIGH
#define DMA_CHANNEL4_PRIORITY_LEVEL					DMA_CHANNEL_PRIORITY_VERY_HIGH
#define DMA_CHANNEL5_PRIORITY_LEVEL					DMA_CHANNEL_PRIORITY_VERY_HIGH
#define DMA_CHANNEL6_PRIORITY_LEVEL					DMA_CHANNEL_PRIORITY_VERY_HIGH


/* Select the Memory Size
 * Options: 1-DMA_MEMORY_SIZE_8_BITS
 * 			2-DMA_MEMORY_SIZE_16_BITS
 * 			3-DMA_MEMORY_SIZE_32_BITS
 **/
#define DMA_CHANNEL0_MEMORY_SIZE					DMA_MEMORY_SIZE_8_BITS
#define DMA_CHANNEL1_MEMORY_SIZE					DMA_MEMORY_SIZE_8_BITS
#define DMA_CHANNEL2_MEMORY_SIZE					DMA_MEMORY_SIZE_8_BITS
#define DMA_CHANNEL3_MEMORY_SIZE					DMA_MEMORY_SIZE_8_BITS
#define DMA_CHANNEL4_MEMORY_SIZE					DMA_MEMORY_SIZE_8_BITS
#define DMA_CHANNEL5_MEMORY_SIZE					DMA_MEMORY_SIZE_8_BITS
#define DMA_CHANNEL6_MEMORY_SIZE					DMA_MEMORY_SIZE_8_BITS


/* Select the Peripheral Size
 * Options: 1-DMA_PERIPHERAL_SIZE_8_BITS
 * 			2-DMA_PERIPHERAL_SIZE_16_BITS
 * 			3-DMA_PERIPHERAL_SIZE_32_BITS
 **/
#define DMA_CHANNEL0_PERIPHERAL_SIZE					DMA_MEMORY_SIZE_8_BITS
#define DMA_CHANNEL1_PERIPHERAL_SIZE					DMA_MEMORY_SIZE_8_BITS
#define DMA_CHANNEL2_PERIPHERAL_SIZE					DMA_MEMORY_SIZE_8_BITS
#define DMA_CHANNEL3_PERIPHERAL_SIZE					DMA_MEMORY_SIZE_8_BITS
#define DMA_CHANNEL4_PERIPHERAL_SIZE					DMA_MEMORY_SIZE_8_BITS
#define DMA_CHANNEL5_PERIPHERAL_SIZE					DMA_MEMORY_SIZE_8_BITS
#define DMA_CHANNEL6_PERIPHERAL_SIZE					DMA_MEMORY_SIZE_8_BITS


/* Enable or Disable the memory increment mode
 * Options: 1-DMA_DISABLE
 * 			2-DMA_ENABLE
 **/
#define DMA_CHANNEL0_MEMORY_INCREMENT_MODE				DMA_ENABLE
#define DMA_CHANNEL1_MEMORY_INCREMENT_MODE				DMA_ENABLE
#define DMA_CHANNEL2_MEMORY_INCREMENT_MODE				DMA_ENABLE
#define DMA_CHANNEL3_MEMORY_INCREMENT_MODE				DMA_ENABLE
#define DMA_CHANNEL4_MEMORY_INCREMENT_MODE				DMA_ENABLE
#define DMA_CHANNEL5_MEMORY_INCREMENT_MODE				DMA_ENABLE
#define DMA_CHANNEL6_MEMORY_INCREMENT_MODE				DMA_ENABLE


/* Enable or Disable the peripheral increment mode
 * Options: 1-DMA_DISABLE
 * 			2-DMA_ENABLE
 **/
#define DMA_CHANNEL0_PERIPHERAL_INCREMENT_MODE			DMA_DISABLE
#define DMA_CHANNEL1_PERIPHERAL_INCREMENT_MODE			DMA_ENABLE
#define DMA_CHANNEL2_PERIPHERAL_INCREMENT_MODE			DMA_ENABLE
#define DMA_CHANNEL3_PERIPHERAL_INCREMENT_MODE			DMA_DISABLE
#define DMA_CHANNEL4_PERIPHERAL_INCREMENT_MODE			DMA_ENABLE
#define DMA_CHANNEL5_PERIPHERAL_INCREMENT_MODE			DMA_ENABLE
#define DMA_CHANNEL6_PERIPHERAL_INCREMENT_MODE			DMA_ENABLE


/* Enable or Disable the circular mode
 * Options: 1-DMA_DISABLE
 * 			2-DMA_ENABLE
 **/
#define DMA_CHANNEL0_CIRCULAR_MODE						DMA_DISABLE
#define DMA_CHANNEL1_CIRCULAR_MODE						DMA_DISABLE
#define DMA_CHANNEL2_CIRCULAR_MODE						DMA_DISABLE
#define DMA_CHANNEL3_CIRCULAR_MODE						DMA_DISABLE
#define DMA_CHANNEL4_CIRCULAR_MODE						DMA_DISABLE
#define DMA_CHANNEL5_CIRCULAR_MODE						DMA_DISABLE
#define DMA_CHANNEL6_CIRCULAR_MODE						DMA_DISABLE


/* Choose the data transfer direction
 * Options: 1-DMA_READ_FROM_PERIPHERAL
 * 			2-DMA_READ_FROM_MEMORY
 **/
#define DMA_CHANNEL0_DATA_TRANSFER_DIRECTION 			DMA_READ_FROM_MEMORY
#define DMA_CHANNEL1_DATA_TRANSFER_DIRECTION 			DMA_READ_FROM_PERIPHERAL
#define DMA_CHANNEL2_DATA_TRANSFER_DIRECTION 			DMA_READ_FROM_PERIPHERAL
#define DMA_CHANNEL3_DATA_TRANSFER_DIRECTION 			DMA_READ_FROM_MEMORY
#define DMA_CHANNEL4_DATA_TRANSFER_DIRECTION 			DMA_READ_FROM_PERIPHERAL
#define DMA_CHANNEL5_DATA_TRANSFER_DIRECTION 			DMA_READ_FROM_PERIPHERAL
#define DMA_CHANNEL6_DATA_TRANSFER_DIRECTION 			DMA_READ_FROM_PERIPHERAL


/* Enable or Disable transfer error interrupt enable
 * Options: 1-DMA_DISABLE
 * 			2-DMA_ENABLE
 **/
#define DMA_CHANNEL0_TRANSFER_ERROR_INTERRUPT_EN		DMA_DISABLE
#define DMA_CHANNEL1_TRANSFER_ERROR_INTERRUPT_EN		DMA_DISABLE
#define DMA_CHANNEL2_TRANSFER_ERROR_INTERRUPT_EN		DMA_DISABLE
#define DMA_CHANNEL3_TRANSFER_ERROR_INTERRUPT_EN		DMA_DISABLE
#define DMA_CHANNEL4_TRANSFER_ERROR_INTERRUPT_EN		DMA_DISABLE
#define DMA_CHANNEL5_TRANSFER_ERROR_INTERRUPT_EN		DMA_DISABLE
#define DMA_CHANNEL6_TRANSFER_ERROR_INTERRUPT_EN		DMA_DISABLE


/* Enable or Disable half transfer interrupt enable
 * Options: 1-DMA_DISABLE
 * 			2-DMA_ENABLE
 **/
#define DMA_CHANNEL0_HALF_TRANSFER_INTERRUPT_EN			DMA_DISABLE
#define DMA_CHANNEL1_HALF_TRANSFER_INTERRUPT_EN			DMA_DISABLE
#define DMA_CHANNEL2_HALF_TRANSFER_INTERRUPT_EN			DMA_DISABLE
#define DMA_CHANNEL3_HALF_TRANSFER_INTERRUPT_EN			DMA_DISABLE
#define DMA_CHANNEL4_HALF_TRANSFER_INTERRUPT_EN			DMA_DISABLE
#define DMA_CHANNEL5_HALF_TRANSFER_INTERRUPT_EN			DMA_DISABLE
#define DMA_CHANNEL6_HALF_TRANSFER_INTERRUPT_EN			DMA_DISABLE


/* Enable or Disable transfer complete interrupt enable
 * Options: 1-DMA_DISABLE
 * 			2-DMA_ENABLE
 **/
#define DMA_CHANNEL0_TRANSFER_COMPLETE_INTERRUPT_EN		DMA_DISABLE
#define DMA_CHANNEL1_TRANSFER_COMPLETE_INTERRUPT_EN		DMA_DISABLE
#define DMA_CHANNEL2_TRANSFER_COMPLETE_INTERRUPT_EN		DMA_DISABLE
#define DMA_CHANNEL3_TRANSFER_COMPLETE_INTERRUPT_EN		DMA_ENABLE
#define DMA_CHANNEL4_TRANSFER_COMPLETE_INTERRUPT_EN		DMA_DISABLE
#define DMA_CHANNEL5_TRANSFER_COMPLETE_INTERRUPT_EN		DMA_DISABLE
#define DMA_CHANNEL6_TRANSFER_COMPLETE_INTERRUPT_EN		DMA_DISABLE



#endif /* DMA_CONFIG_H_ */
